swagger: 2.0
info:
  title: Aquo API
  version: 1.0
host: %{dotwebstack.config.host}
basePath: /api/aquo
produces:
  - application/json
paths:
  /search/begrippen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/ApiSearchConceptenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - ?begrip 
            items:
              type: object
              properties:
                begrip:
                  type: string
                  format: string
                begrip_label:
                  type: string
                  format: string
                synoniem:
                  type: string
                  format: string
                categorie:
                  type: string
                  format: string
                definitie:
                  type: string
                  format: string
                gevonden_in:
                  type: string
                  format: string
  /search/categorieen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchCategorieenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - ?categorie 
              - ?categorie_label 
            items:
              type: object
              properties:
                categorie:
                  type: string
                  format: string
                categorie_label:
                  type: string
                  format: string
  /search/domeintabellen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchDomeinenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - ?domeintabel 
              - ?domeintabel_label 
            items:
              type: object
              properties:
                domeintabel:
                  type: string
                  format: string
                domeintabel_label:
                  type: string
                  format: string
  /search/domeinwaarden/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchDomeinWaardeData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - label_waarde
              - domeintabel_waarde
              - domeintabel_waarde_label
              - CASnummer 
              - Code 
              - ID 
              - gevonden_in
            items:
              type: object
              properties:
                label_waarde:
                  type: string
                  format: string
                domeintabel_waarde:
                  type: string
                  format: string
                domeintabel_waarde_label:
                  type: string
                  format: string
                CASnummer:
                  type: string
                  format: string
                Code:
                  type: string
                  format: string
                ID:
                  type: string
                  format: string
                gevonden_in:
                  type: string
                  format: string
definitions:
  Concept:
    type: object
    required:
      - type
    properties:
      afbeelding:
        type: string
        x-dotwebstack-ldpath: "foaf:depiction :: xsd:string"
      beschrevenDoor:
        type: string
        x-dotwebstack-ldpath: "wdrs:describedby :: xsd:string"
      beschrijving:
        type: string
        x-dotwebstack-ldpath: "dct:description :: xsd:string"
      bestaatUit:
        type: array
        x-dotwebstack-ldpath: "thes:narrowerPartitive :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      breidtUit:
        type: string
        x-dotwebstack-ldpath: "skoslex:expands :: xsd:string"
      bron:
        type: string
        x-dotwebstack-ldpath: "dct:source :: xsd:string"
      contact:
        type: string
        x-dotwebstack-ldpath: "dcat:contactPoint :: xsd:string"
      dataset:
        type: array
        x-dotwebstack-ldpath: "dcat:dataset :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      definitie:
        type: string
        x-dotwebstack-ldpath: "skos:definition :: xsd:string"
      distributie:
        type: array
        x-dotwebstack-ldpath: "dcat:distribution :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      domein:
        type: string
        x-dotwebstack-ldpath: "skos:inScheme :: xsd:string"
      download:
        type: string
        x-dotwebstack-ldpath: "dcat:downloadURL :: xsd:string"
      emailadres:
        type: string
        x-dotwebstack-ldpath: "foaf:mbox :: xsd:string"
      gedelegeerdAan:
        type: array
        x-dotwebstack-ldpath: "skoslex:delegatedTo :: xsd:string"        
      heeftBetrekkingOp:
        type: array
        x-dotwebstack-ldpath: "skos:semanticRelation :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      gepubliceerd:
        type: string
        x-dotwebstack-ldpath: "dct:issued :: xsd:string"
      gepubliceerdDoor:
        type: string
        x-dotwebstack-ldpath: "dct:publisher :: xsd:string"
      homepage:
        type: string
        x-dotwebstack-ldpath: "foaf:homepage :: xsd:string"
      isBrederDan:
        type: array
        x-dotwebstack-ldpath: "skos:broadMatch :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isEngerDan:
        type: array
        x-dotwebstack-ldpath: "skos:narrowMatch :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isGeneralisatieVan:
        type: array
        x-dotwebstack-ldpath: "thes:narrowerGeneric :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isHetzelfdeAls:
        type: array
        x-dotwebstack-ldpath: "skos:exactMatch :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isOnderdeelVan:
        type: array
        x-dotwebstack-ldpath: "thes:broaderPartitive :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isOngeveerHetzelfdeAls:
        type: array
        x-dotwebstack-ldpath: "skos:closeMatch :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      isSpecialisatieVan:
        type: array
        x-dotwebstack-ldpath: "thes:broaderGeneric :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      laatsteWijziging:
        type: string
        x-dotwebstack-ldpath: "dct:modified :: xsd:string"
      licentie:
        type: string
        x-dotwebstack-ldpath: "dct:license :: xsd:string"
      lid:
        type: array
        x-dotwebstack-ldpath: "skos:member :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      object:
        type: string
        x-dotwebstack-ldpath: "skoslex:object :: xsd:string"
      oin:
        type: string
        x-dotwebstack-ldpath: "org:identifier :: xsd:string"
      metadata:
        type: string
        x-dotwebstack-ldpath: "foaf:isPrimaryTopicOf :: xsd:string"
      naam:
        type: array
        x-dotwebstack-ldpath: "rdfs:label :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      namensOrganisatie:
        type: string
        x-dotwebstack-ldpath: "prov:actedOnBehalfOf :: xsd:string"
      note:
        type: string
        x-dotwebstack-ldpath: "vcard:note :: xsd:string"
      notitie:
        type: string
        x-dotwebstack-ldpath: "skos:notation :: xsd:string"
      rechten:
        type: string
        x-dotwebstack-ldpath: "dct:rights :: xsd:string"
      relatie:
        type: string
        x-dotwebstack-ldpath: "dct:relation :: xsd:string"
      sleutelwoord:
        type: string
        x-dotwebstack-ldpath: "dcat:keyword :: xsd:string"
      synoniem:
        type: "array"
        x-dotwebstack-ldpath: "skos:altLabel :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      taal:
        type: string
        x-dotwebstack-ldpath: "dct:language :: xsd:string"
      taxonomy:
        type: string
        x-dotwebstack-ldpath: "dcat:themeTaxonomy :: xsd:string"
      tekstbron:
        type: string
        x-dotwebstack-ldpath: "dc:source :: xsd:string"
      telefoon:
        type: string
        x-dotwebstack-ldpath: "vcard:hasTelephone :: xsd:string"
      term:
        type: string
        x-dotwebstack-ldpath: "skos:prefLabel :: xsd:string"
      titel:
        type: string
        x-dotwebstack-ldpath: "dct:title :: xsd:string"
      toegangsUrl:
        type: string
        x-dotwebstack-ldpath: "dcat:accessURL :: xsd:string"
      toelichting:
        type: string
        x-dotwebstack-ldpath: "skos:scopeNote :: xsd:string"
      type:
        type: array
        x-dotwebstack-ldpath: "rdf:type"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
      uitleg:
        type: string
        x-dotwebstack-ldpath: "rdfs:comment :: xsd:string"
      url:
        type: string
        x-dotwebstack-ldpath: "vcard:hasURL :: xsd:string"
      versie:
        type: string
        x-dotwebstack-ldpath: "adms:version :: xsd:string"
      versienotities:
        type: string
        x-dotwebstack-ldpath: "adms:versionNotes :: xsd:string"
      volledigeNaam:
        type: string
        x-dotwebstack-ldpath: "foaf:givenName :: xsd:string"
      website:
        type: string
        x-dotwebstack-ldpath: "dcat:landingPage :: xsd:string"
      werkingsgebied:
        type: string
        x-dotwebstack-ldpath: "dct:spatial :: xsd:string"
      zieOok:
        type: array
        x-dotwebstack-ldpath: "skos:relatedMatch :: xsd:string"
        items:
          type: string
          x-dotwebstack-ldpath: ". :: xsd:string"
